steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA",
        "--build-arg",
        "GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}",
        "--build-arg",
        "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}",
        "--build-arg",
        "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}",
        "--build-arg",
        "NEXTAUTH_URL=${_NEXTAUTH_URL}",
        ".",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
