steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA,
        "--build-arg",
        "GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}",
        "--build-arg",
        "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}",
        "--build-arg",
        "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}",
        "--build-arg",
        "NEXTAUTH_URL=${_NEXTAUTH_URL}",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["run", "deploy", "sawada-management-console", "--image", "gcr.io/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA", "--region", "us-central1"]

images:
- gcr.io/$PROJECT_ID/sawada-management-console/image
options:
  logging: CLOUD_LOGGING_ONLY
