# 1. Secret manager から環境変数を取得してymlファイルに書き込む
# 2. gcloud app deploy
#
#
#

steps:
  - id: get-env-vars-from-SecretManager
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: [
        "-eEuo",
        "pipefail",
        "-c",
        "cat <<EOF > .env.production
        GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID
        GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET
        NEXTAUTH_SECRET=$$NEXTAUTH_SECRET
        NEXTAUTH_URL=$$NEXTAUTH_URL
        EOF",
      ]
    secretEnv:
      [
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "NEXTAUTH_SECRET",
        "NEXTAUTH_URL",
      ]
  - id: deploy-to-AppEngine
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args: ["app", "deploy", "gae.yaml"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/1
      env: GOOGLE_CLIENT_ID
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_SECRET/versions/1
      env: GOOGLE_CLIENT_SECRET
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_SECRET/versions/1
      env: NEXTAUTH_SECRET
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_URL/versions/1
      env: NEXTAUTH_URL
options:
  logging: CLOUD_LOGGING_ONLY
