steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "gcr.io/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "sawada-management-console",
        "--image",
        "gcr.io/$PROJECT_ID/sawada-management-console/image:$COMMIT_SHA",
        "--region",
        "us-central1",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      [
        "-c",
        "gcloud run services update sawada-management-console --concurrency 1 --cpu 1 --update-env-vars GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET,NEXTAUTH_SECRET=$$NEXTAUTH_SECRET,NEXTAUTH_URL=$$NEXTAUTH_URL --region us-central1",
      ]
    secretEnv:
      [
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "NEXTAUTH_SECRET",
        "NEXTAUTH_URL",
      ]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/1
      env: GOOGLE_CLIENT_ID
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_SECRET/versions/1
      env: GOOGLE_CLIENT_SECRET
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_SECRET/versions/1
      env: NEXTAUTH_SECRET
    - versionName: projects/$PROJECT_ID/secrets/NEXTAUTH_URL/versions/1
      env: NEXTAUTH_URL

images:
  - gcr.io/$PROJECT_ID/sawada-management-console/image
options:
  logging: CLOUD_LOGGING_ONLY
