FROM node:18-alpine AS build-image

WORKDIR /app
COPY . /app/

RUN yarn && yarn build

FROM node:18-alpine AS run-image

ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL

ENV GOOGLE_CLIENT_ID ${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET ${GOOGLE_CLIENT_SECRET}
ENV NEXTAUTH_SECRET ${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL ${NEXTAUTH_URL}

WORKDIR /app
COPY --from=build-image /app/ /app/

EXPOSE 3000
CMD [ "yarn", "start" ]