name: build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: yarn
        run: yarn

      - name: yarn build
        run: yarn build
