name: cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: show current directory
        run: pwd; ls -lAh

      - name: docker compose up
        run: docker compose up -d --force-recreate
