name: cd

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  push_imagee_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: get lower case repository name
        id: get_repo_name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Build and push
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }}-latest
          docker push ghcr.io/${REPO}:latest
